CREATE TABLE receive (
  coagyear varchar,
  projectid varchar,
  subprojectid varchar,
  datereceived varchar,
  receiveno varchar,
  amountreceivedusd varchar,
  exchangerate varchar,
  amountreceivedthb varchar,
  gain varchar,
  chequereceived varchar,
  remark varchar,
  _datecreated varchar,
  _usercreated varchar,
  _dateupdated varchar,
  _userupdated varchar);